/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pmtest */

#ifndef _Included_pmtest
#define _Included_pmtest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pmtest
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pmtest_init
  (JNIEnv *, jobject);

/*
 * Class:     pmtest
 * Method:    yes
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_pmtest_yes
  (JNIEnv *, jobject);

/*
 * Class:     pmtest
 * Method:    no
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_pmtest_no
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
